"""
Einstein Trust Layer Policy Importer

Imports Einstein Trust Layer guardrail configuration from Salesforce
and converts it to Stratix policy-as-code YAML format.

Supports:
- Guardrail rules extraction via Metadata API
- Data masking policy import
- Conversion to Stratix YAML policy DSL
- Round-trip: import, evaluate, export updated policies

Reference: https://developer.salesforce.com/docs/einstein/genai/guide/trust.html
"""

from __future__ import annotations

import logging

from layerlens.instrument.adapters.frameworks.agentforce.auth import SalesforceConnection
from layerlens.instrument.adapters.frameworks.agentforce.models import (
    TrustLayerConfig,
    TrustLayerGuardrail,
)

logger = logging.getLogger(__name__)

# Metadata API types for Trust Layer config
_TRUST_LAYER_METADATA_TYPES = [
    "GenAiPlugin",
    "GenAiFunction",
]

# Default guardrail names in Einstein Trust Layer
_DEFAULT_GUARDRAILS = [
    "toxicity_detection",
    "pii_detection",
    "prompt_injection",
    "hallucination_detection",
]


class TrustLayerImporter:
    """
    Import Einstein Trust Layer configuration and convert to Stratix policy.

    Usage:
        importer = TrustLayerImporter(connection=connection)
        config = importer.fetch_config()
        yaml_str = importer.to_stratix_policy(config)
    """

    def __init__(self, connection: SalesforceConnection) -> None:
        self._connection = connection

    def fetch_config(self) -> TrustLayerConfig:
        """
        Fetch Einstein Trust Layer configuration from Salesforce.

        Queries the Setup metadata to extract guardrail rules,
        data masking settings, and audit configuration.

        Returns:
            TrustLayerConfig with all detected guardrails and settings.
        """
        guardrails: list[TrustLayerGuardrail] = []

        # Query for GenAI guardrail metadata
        try:
            records = self._connection.query(
                "SELECT DeveloperName, Language, MasterLabel "
                "FROM GenAiPlugin "
                "WHERE IsDeleted = false "
                "ORDER BY DeveloperName ASC"
            )
            for record in records:
                name = record.get("DeveloperName", "")
                if name:
                    guardrails.append(
                        TrustLayerGuardrail(
                            name=name,
                            type=self._classify_guardrail(name),
                            enabled=True,
                        )
                    )
        except Exception as e:
            logger.warning("Failed to query GenAiPlugin metadata: %s", e)

        # Add default guardrails if none found (Trust Layer has built-in ones)
        if not guardrails:
            for name in _DEFAULT_GUARDRAILS:
                guardrails.append(
                    TrustLayerGuardrail(
                        name=name,
                        type=self._classify_guardrail(name),
                        enabled=True,
                    )
                )

        return TrustLayerConfig(
            guardrails=guardrails,
            data_masking_enabled=False,  # Disabled for agents per SF docs
            zero_data_retention=True,
            audit_trail_enabled=True,
        )

    def to_stratix_policy(
        self,
        config: TrustLayerConfig,
        policy_name: str = "agentforce_trust_layer",
        policy_version: str = "1.0.0",
    ) -> str:
        """
        Convert a TrustLayerConfig to Stratix policy-as-code YAML.

        Args:
            config: The Trust Layer configuration to convert.
            policy_name: Name for the generated policy.
            policy_version: Version string for the policy.

        Returns:
            YAML string representing a Stratix policy document.
        """
        rules: list[str] = []

        for guardrail in config.guardrails:
            action = "block" if guardrail.action == "block" else "warn"
            threshold = guardrail.threshold if guardrail.threshold is not None else 0.8

            rule_yaml = (
                f"  - name: {guardrail.name}\n"
                f'    description: "Imported from Einstein Trust Layer: {guardrail.type}"\n'
                f"    type: {guardrail.type}\n"
                f"    enabled: {str(guardrail.enabled).lower()}\n"
                f"    threshold: {threshold}\n"
                f"    action: {action}\n"
                f"    source: einstein_trust_layer"
            )
            rules.append(rule_yaml)

        rules_block = "\n".join(rules) if rules else "  []"

        yaml_output = (
            f"# Stratix Policy - Imported from Einstein Trust Layer\n"
            f"# Generated by: stratix.sdk.python.adapters.agentforce.trust_layer\n"
            f"# Source: Salesforce Einstein Trust Layer\n"
            f"\n"
            f"policy:\n"
            f"  name: {policy_name}\n"
            f'  version: "{policy_version}"\n'
            f'  description: "Policy imported from Salesforce Einstein Trust Layer"\n'
            f"  source: salesforce_agentforce\n"
            f"\n"
            f"settings:\n"
            f"  data_masking: {str(config.data_masking_enabled).lower()}\n"
            f"  zero_data_retention: {str(config.zero_data_retention).lower()}\n"
            f"  audit_trail: {str(config.audit_trail_enabled).lower()}\n"
            f"\n"
            f"rules:\n"
            f"{rules_block}\n"
        )

        return yaml_output

    def import_and_convert(
        self,
        policy_name: str = "agentforce_trust_layer",
    ) -> tuple[TrustLayerConfig, str]:
        """
        Convenience method: fetch config and convert to YAML in one call.

        Args:
            policy_name: Name for the generated policy.

        Returns:
            Tuple of (TrustLayerConfig, YAML string).
        """
        config = self.fetch_config()
        yaml_str = self.to_stratix_policy(config, policy_name=policy_name)
        return config, yaml_str

    @staticmethod
    def _classify_guardrail(name: str) -> str:
        """Classify a guardrail name into a guardrail type."""
        name_lower = name.lower()
        if "toxic" in name_lower or "harm" in name_lower:
            return "toxicity"
        if "pii" in name_lower or "mask" in name_lower or "privacy" in name_lower:
            return "pii"
        if "injection" in name_lower or "jailbreak" in name_lower:
            return "prompt_injection"
        if "hallucin" in name_lower or "ground" in name_lower:
            return "hallucination"
        return "custom"
