[mypy]
pretty = True
hide_error_codes = False

strict_equality = True
implicit_reexport = True
check_untyped_defs = True
implicit_optional = False

warn_return_any = True
warn_unreachable = True
warn_unused_configs = True

warn_unused_ignores = True
warn_redundant_casts = True

disallow_any_generics = True
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_subclassing_any = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
cache_fine_grained = True

[mypy-click]
ignore_missing_imports = True

[mypy-layerlens.cli.*]
ignore_missing_imports = True
disallow_untyped_decorators = False
disallow_untyped_defs = False
disallow_any_generics = False

[mypy-layerlens.instrument.adapters.frameworks.*]
ignore_errors = True

[mypy-layerlens.instrument.adapters.providers.*]
ignore_errors = True

[mypy-layerlens.instrument.adapters.protocols.*]
ignore_errors = True
