"""Generator for the OpenInference cross-language conformance corpus.

Emits ``spans.otlp.json`` — a proto3-JSON ``ExportTraceServiceRequest`` carrying
one span per mapping lane. It is the SHARED INPUT fed to BOTH the Python importer
(``layerlens.instrument.adapters.frameworks.openinference.span_to_events``) and the
Go OTLP bridge (``atlas-app/apps/otlp-ingest/ingest/openinference.go``), so the two
implementations of the SAME span->event contract can be pinned against each other.

WHAT THIS CORPUS IS — read before trusting it
---------------------------------------------
These spans are SYNTHETIC, DELIBERATELY-CONSTRUCTED CONTRACT INPUTS. They are NOT
a recording of a production run and must never be presented as one. Every lane
exists to exercise one branch of the mapping (a span kind, a fallback, a cap, an
honest omission), including branches a real trace shows only rarely (GUARDRAIL,
EVALUATOR, RERANKER) or that only appear under failure.

They are honest for their purpose — pinning a pure function's dispatch, field
names, and caps — because the ORACLE they are compared against is generated from
the REAL Go bridge, never hand-written. What is asserted is agreement between two
real implementations over a stated input; nothing here is presented as measured
production data.

The attribute KEYS and the LLM lane's values are taken from the real OpenInference
semantic conventions as already exercised by the real wire fixture at
``atlas-app/apps/otlp-ingest/ingest/testdata/otlp-fixtures/03-openinference-arize.otlp.json``
(itself generated by ateam's ``_generator/generate.py``).

Determinism: ids are fixed literals, timestamps are fixed epoch-ns literals, and
the file is written with ``sort_keys=True, indent=2`` + trailing newline. Running
this generator twice produces a byte-identical file.

Run:
    python tests/instrument/adapters/frameworks/oi_conformance/_generate_corpus.py
"""

from __future__ import annotations

import json
import pathlib
from typing import Any, Dict, List

# Fixed span timing: 500ms per span. Both bridges must derive the SAME duration
# (Go duration_ms, Python latency_ms — the D1 rename, see the conformance test).
START_NS = 1_777_593_600_000_000_000
END_NS = 1_777_593_600_500_000_000
TRACE_ID = "8236235c4a945f11b1db2c1559d642fc"

# Content longer than the 2000-char content cap, to pin oiCap/_safe_str agreement.
OVERSIZED = "x" * 5000


def s(v: str) -> Dict[str, Any]:
    return {"stringValue": v}


def i(v: int) -> Dict[str, Any]:
    # proto3-JSON encodes int64 as a STRING (JSON numbers cannot carry uint64).
    return {"intValue": str(v)}


def arr(*vals: float) -> Dict[str, Any]:
    return {"arrayValue": {"values": [{"doubleValue": v} for v in vals]}}


#: (span_id, name, status_code, status_message, attributes) per lane.
#: status code: 0=UNSET 1=OK 2=ERROR (OTel status enum).
LANES: List[Any] = [
    # --- LLM ---------------------------------------------------------------
    (
        "0000000000000001",
        "ChatCompletion",
        1,
        "",
        {
            "openinference.span.kind": s("LLM"),
            "llm.model_name": s("gpt-4o"),
            "llm.provider": s("openai"),
            "llm.system": s("openai"),
            "llm.token_count.prompt": i(312),
            "llm.token_count.completion": i(178),
            "llm.token_count.total": i(490),
            "llm.invocation_parameters": s('{"temperature": 0.0, "max_tokens": 256}'),
            "input.value": s("Score this response for factual accuracy."),
            "output.value": s("Score: 4/5. The response is mostly accurate."),
            "session.id": s("sess-42"),
            "user.id": s("user-7"),
            "metadata": s('{"tenant": "acme"}'),
        },
    ),
    # provider falls back to llm.system when llm.provider is absent (LLM only).
    (
        "0000000000000002",
        "ChatCompletion",
        1,
        "",
        {
            "openinference.span.kind": s("LLM"),
            "llm.model_name": s("claude-3-5-sonnet"),
            "llm.system": s("anthropic"),
        },
    ),
    # D2: status ERROR + message -> error carries the message.
    (
        "0000000000000003",
        "ChatCompletion",
        2,
        "rate limited by upstream",
        {"openinference.span.kind": s("LLM"), "llm.model_name": s("gpt-4o")},
    ),
    # D2 PIN: status OK + a status message -> NO error. A non-errored span that
    # merely carries a description must not be labelled errored.
    (
        "0000000000000004",
        "ChatCompletion",
        1,
        "cache miss; refetched upstream",
        {"openinference.span.kind": s("LLM"), "llm.model_name": s("gpt-4o")},
    ),
    # D2: status ERROR + EMPTY message -> the content-free literal fallback.
    (
        "0000000000000005",
        "ChatCompletion",
        2,
        "",
        {"openinference.span.kind": s("LLM"), "llm.model_name": s("gpt-4o")},
    ),
    # Caps: oversized content must truncate identically on both sides.
    (
        "0000000000000006",
        "ChatCompletion",
        1,
        "",
        {
            "openinference.span.kind": s("LLM"),
            "llm.model_name": s("gpt-4o"),
            "input.value": s(OVERSIZED),
            "output.value": s(OVERSIZED),
        },
    ),
    # A token count arriving as a numeric STRING must be parsed, not dropped.
    (
        "0000000000000007",
        "ChatCompletion",
        1,
        "",
        {
            "openinference.span.kind": s("LLM"),
            "llm.model_name": s("gpt-4o"),
            "llm.token_count.prompt": s("128"),
        },
    ),
    # No model/provider attrs -> the explicit declared-unknown sentinel.
    ("0000000000000008", "openai.chat", 1, "", {"openinference.span.kind": s("LLM")}),
    # --- EMBEDDING ---------------------------------------------------------
    # D4 PIN: the FLATTENED form real instrumentors emit (OTel attributes cannot
    # hold nested objects, so `embedding.embeddings` as a list is unreachable on
    # the wire). Two distinct indices across four keys.
    (
        "0000000000000009",
        "embedding",
        1,
        "",
        {
            "openinference.span.kind": s("EMBEDDING"),
            "embedding.model_name": s("text-embedding-3-small"),
            "llm.provider": s("openai"),
            "llm.token_count.prompt": i(64),
            "embedding.embeddings.0.embedding.vector": arr(0.1, 0.2),
            "embedding.embeddings.0.embedding.text": s("first chunk"),
            "embedding.embeddings.1.embedding.vector": arr(0.3, 0.4),
            "embedding.embeddings.1.embedding.text": s("second chunk"),
            "input.value": s("embed these chunks"),
        },
    ),
    # D4 honesty: no embeddings attrs at all -> embedding_count OMITTED, not 0.
    (
        "000000000000000a",
        "embedding",
        1,
        "",
        {
            "openinference.span.kind": s("EMBEDDING"),
            "embedding.model_name": s("text-embedding-3-small"),
        },
    ),
    # EMBEDDING has NO llm.system provider fallback (deliberate, mirrors Go).
    (
        "000000000000000b",
        "embedding",
        1,
        "",
        {
            "openinference.span.kind": s("EMBEDDING"),
            "embedding.model_name": s("m"),
            "llm.system": s("openai"),
        },
    ),
    # --- TOOL --------------------------------------------------------------
    # D3 PIN: an EMPTY tool.parameters must fall through to input.value rather
    # than shadow it — otherwise the real tool input is silently LOST.
    (
        "000000000000000c",
        "web_search",
        1,
        "",
        {
            "openinference.span.kind": s("TOOL"),
            "tool.name": s("web_search"),
            "tool.description": s("Search the public web"),
            "tool.parameters": s(""),
            "input.value": s('{"query": "layerlens pricing"}'),
            "output.value": s("3 results"),
        },
    ),
    # D3: a NON-empty tool.parameters still wins over input.value.
    (
        "000000000000000d",
        "web_search",
        1,
        "",
        {
            "openinference.span.kind": s("TOOL"),
            "tool.name": s("web_search"),
            "tool.parameters": s('{"q": "real params"}'),
            "input.value": s("ignored"),
        },
    ),
    # No tool.name -> the span name is the tool identity.
    ("000000000000000e", "lookup_order", 1, "", {"openinference.span.kind": s("TOOL")}),
    # --- RERANKER ----------------------------------------------------------
    (
        "000000000000000f",
        "rerank",
        1,
        "",
        {
            "openinference.span.kind": s("RERANKER"),
            "reranker.model_name": s("rerank-v3"),
            "reranker.top_k": i(5),
            "reranker.query": s("best pricing page"),
        },
    ),
    # --- RETRIEVER ---------------------------------------------------------
    (
        "0000000000000010",
        "retrieve",
        1,
        "",
        {
            "openinference.span.kind": s("RETRIEVER"),
            "input.value": s("layerlens pricing"),
            "retrieval.documents.0.document.id": s("a"),
            "retrieval.documents.0.document.score": {"doubleValue": 0.91},
            "retrieval.documents.1.document.id": s("b"),
            "retrieval.documents.2.document.id": s("c"),
        },
    ),
    # An honest MEASURED zero: a retriever that returned nothing.
    ("0000000000000011", "retrieve", 1, "", {"openinference.span.kind": s("RETRIEVER")}),
    # --- AGENT / CHAIN (each emits a PAIR from one span) --------------------
    (
        "0000000000000012",
        "research_agent",
        1,
        "",
        {
            "openinference.span.kind": s("AGENT"),
            "input.value": s("research the pricing question"),
            "output.value": s("pricing is usage-based"),
        },
    ),
    (
        "0000000000000013",
        "rag_chain",
        1,
        "",
        {
            "openinference.span.kind": s("CHAIN"),
            "input.value": s("chain in"),
            "output.value": s("chain out"),
        },
    ),
    # --- GUARDRAIL ---------------------------------------------------------
    # Triggered (status ERROR) -> policy.violation.
    (
        "0000000000000014",
        "safety_check",
        2,
        "blocked: policy hit",
        {"openinference.span.kind": s("GUARDRAIL"), "output.value": s("BLOCKED")},
    ),
    # Passed (status OK) -> an ordinary tool.call. No violation is manufactured.
    (
        "0000000000000015",
        "safety_check",
        1,
        "",
        {"openinference.span.kind": s("GUARDRAIL"), "output.value": s("PASS")},
    ),
    # --- EVALUATOR ---------------------------------------------------------
    (
        "0000000000000016",
        "hallucination_eval",
        1,
        "",
        {"openinference.span.kind": s("EVALUATOR"), "output.value": s("PASS")},
    ),
    # --- UNKNOWN default (nothing is ever dropped) -------------------------
    (
        "0000000000000017",
        "weird_span",
        1,
        "",
        {
            "openinference.span.kind": s("SOMETHING_NEW"),
            "input.value": s("in"),
            "output.value": s("out"),
        },
    ),
    # A PRESENT-but-empty kind still routes to agent.interaction, never dropped.
    (
        "0000000000000018",
        "empty_kind",
        1,
        "",
        {"openinference.span.kind": s(""), "input.value": s("in")},
    ),
]


def build() -> Dict[str, Any]:
    spans: List[Dict[str, Any]] = []
    for span_id, name, code, message, attrs in LANES:
        span: Dict[str, Any] = {
            "attributes": [{"key": k, "value": v} for k, v in sorted(attrs.items())],
            "endTimeUnixNano": str(END_NS),
            "kind": 3,
            "name": name,
            "parentSpanId": "",
            "spanId": span_id,
            "startTimeUnixNano": str(START_NS),
            "status": {"code": code, "message": message},
            "traceId": TRACE_ID,
        }
        spans.append(span)
    return {
        "resourceSpans": [
            {
                "resource": {
                    "attributes": [
                        {"key": "service.name", "value": s("oi-conformance")},
                    ]
                },
                "scopeSpans": [
                    {
                        "scope": {
                            "name": "openinference.instrumentation.openai",
                            "version": "0.1.18",
                        },
                        "spans": spans,
                    }
                ],
            }
        ]
    }


def main() -> None:
    out = pathlib.Path(__file__).parent / "spans.otlp.json"
    out.write_text(json.dumps(build(), indent=2, sort_keys=True) + "\n")
    print(f"wrote {out} ({len(LANES)} spans)")


if __name__ == "__main__":
    main()
